# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_stats <- function(observed, predicted) {
    .Call(`_rEDM_compute_stats`, observed, predicted)
}

start_profiler <- function() {
    .Call(`_rEDM_start_profiler`)
}

stop_profiler <- function() {
    .Call(`_rEDM_stop_profiler`)
}

